# Конфигурация сервисов для системы автодозвона
services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: dialer_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dialer_db
      POSTGRES_USER: dialer_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - dialer_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dialer_user -d dialer_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis для кэширования
  redis:
    image: redis:7-alpine
    container_name: dialer_redis
    restart: unless-stopped
    command: redis-server --requirepass redis_password_123
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - dialer_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # FreeSWITCH (публичный образ от ittoyxk)
  freeswitch:
    image: ghcr.io/ittoyxk/freeswitch:v1.10.11
    container_name: dialer_freeswitch
    restart: unless-stopped
    ports:
      - "5060:5060/udp"    # SIP
      - "5080:5080/udp"    # SIP альтернативный
      - "8021:8021"        # ESL (Event Socket Library)
      - "16384-16394:16384-16394/udp"  # RTP медиа
    volumes:
      - ./freeswitch/conf:/usr/local/freeswitch/conf
      - freeswitch_logs:/usr/local/freeswitch/log
      - freeswitch_sounds:/usr/local/freeswitch/sounds
    networks:
      - dialer_network
    environment:
      - DAEMON=false
      - TZ=Europe/Moscow
    command: ["freeswitch", "-nc", "-nonat"]
    healthcheck:
      test: ["CMD", "fs_cli", "-x", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: dialer_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/logs:/app/logs
      - ./audio:/app/audio
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://dialer_user:secure_password_123@postgres:5432/dialer_db
      - REDIS_URL=redis://:redis_password_123@redis:6379
      - FREESWITCH_HOST=freeswitch
      - FREESWITCH_PORT=8021
      - FREESWITCH_PASSWORD=ClueCon
      - JWT_SECRET=e556e588ee21e16ed4485a2c94149363ec8c85c881801895ecce9d786d41084e445fca510a8cf7d6fe771e65d956e23d1e0b40b6b82029b1920bb034c17a5149
      - MAX_CONCURRENT_CALLS=10
      - CALLS_PER_MINUTE=30
      - LOG_LEVEL=info
      - MONITORING_ENABLED=true
      - CORS_ORIGIN=http://localhost:5173
      - SIP_PROVIDER_HOST=sip.example.com
      - SIP_PROVIDER_USERNAME=test_user
      - SIP_PROVIDER_PASSWORD=test_password
      - SIP_CALLER_ID_NUMBER=+70000000000
    networks:
      - dialer_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      freeswitch:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Vue.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: dialer_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
      - VITE_WS_URL=ws://localhost:3000
    networks:
      - dialer_network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  freeswitch_logs:
    driver: local
  freeswitch_sounds:
    driver: local

networks:
  dialer_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 