name: dialer-ready

services:
  postgres:
    image: postgres:15-alpine
    container_name: dialer_postgres_ready
    environment:
      - POSTGRES_DB=dialer
      - POSTGRES_USER=dialer
      - POSTGRES_PASSWORD=dialer_pass_2025
    volumes:
      - postgres_data_ready:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dialer_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dialer"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: dialer_redis_ready
    volumes:
      - redis_data_ready:/data
    ports:
      - "6379:6379"
    networks:
      - dialer_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # ГОТОВЫЙ ОБРАЗ ASTERISK (быстрый старт)
  asterisk:
    image: mlan/asterisk:base
    container_name: dialer_asterisk_ready
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5038:5038/tcp"
      - "10000-10020:10000-10020/udp"
    volumes:
      - asterisk_config_ready:/srv
      - ./docker/asterisk/conf:/etc/asterisk:ro
    networks:
      - dialer_network
    restart: unless-stopped
    environment:
      - SYSLOG_LEVEL=4
    healthcheck:
      test: ["CMD", "asterisk", "-r", "-x", "core show version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    image: dailer-backend:latest
    container_name: dialer_backend_ready
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      asterisk:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=dialer
      - DB_USER=dialer
      - DB_PASSWORD=dialer_pass_2025
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - VOIP_PROVIDER=asterisk
      - ASTERISK_HOST=asterisk
      - ASTERISK_PORT=5038
      - ASTERISK_USERNAME=admin
      - ASTERISK_PASSWORD=dailer_admin_2025
    ports:
      - "3001:3001"
    volumes:
      - backend_uploads_ready:/app/uploads
    networks:
      - dialer_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: dailer-frontend:latest
    container_name: dialer_frontend_ready
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - dialer_network
    restart: unless-stopped

volumes:
  postgres_data_ready:
  redis_data_ready:
  asterisk_config_ready:
  backend_uploads_ready:

networks:
  dialer_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 